server:
  port: 8080

spring:
  application:
    name: maestria-api-gateway

  cloud:
    gateway:
      routes:
        - id: user_service_route
          uri: http://user-service:8081

          predicates:
            - Path=/api/v1/users/**, /api/v1/admin/**, /login/oauth2/**, /oauth2/**

        - id: course_service_route
          uri: http://course-service:8082

          predicates:
              - Path=/api/v1/courses/**

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE